FROM quay.io/centos/centos:stream9

ARG VERSION=4.4
ARG VERSION_XYZ=4.4.14

RUN dnf -y update && \
    dnf clean all

RUN dnf -y --nodocs --setopt install_weak_deps=False install \
    https://yum.theforeman.org/candlepin/${VERSION}/el9/x86_64/candlepin-${VERSION_XYZ}-1.el9.noarch.rpm \
    https://yum.theforeman.org/candlepin/${VERSION}/el9/x86_64/candlepin-selinux-${VERSION_XYZ}-1.el9.noarch.rpm && \
    dnf clean all

CMD ["/usr/libexec/tomcat/server", "start"]
